# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dormo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      VITE_API_BASE_URL: https://dormo.azurewebsites.net
      API_VERSION: /api/v1.0

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://emsidev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2e87c5d0f7ed4a76b1e4ddf295c713d1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c7102553089740f4ab4acae61daf9b73 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: emsidev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2e87c5d0f7ed4a76b1e4ddf295c713d1 }}/dormo-app:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          API_VERSION=${{ secrets.API_VERSION }}
          PROD_CONNECTION_STRING=${{ secrets.PROD_CONNECTION_STRING }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dormo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0d7ede2fe2ac4956813ff2ea868074fb }}
        images: 'emsidev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2e87c5d0f7ed4a76b1e4ddf295c713d1 }}/dormo-app:${{ github.sha }}'
